### ISSUE TITLE
Should we add more debugging information to the app?

### ISSUE THREAD

**Issue by omajid** [openshift-s2i/s2i-aspnet-example#58]
Folowing up from https://github.com/redhat-developer/s2i-dotnetcore-ex/pull/55, and based on seeing some customer cases, I wonder if it would be beneficial if the sample app told us a few things straight up so we didn't to do a few rounds of emails with customers asking for it:

- .NET Version
- Value of *some* environment variables, like `ASPNETCORE_URLS`
- @omajid to add more

https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/aspnetapp/Pages/Index.cshtml seems like something we could adapt/borrow from.

**Comment by omajid** [comment]
cc @tmds @aslicerh

**Comment by tmds** [comment]
> .NET Version
Value of some environment variables, like ASPNETCORE_URLS

The s2i image has envvars that print out this information, not just for this app, but for any app the customer is building.
It would be good if our customers and support engineers get familiar with those.

**Comment by omajid** [comment]
> The s2i image has envvars that print out this information, not just for this app, but for any app the customer is building.
It would be good if our customers and support engineers get familiar with those.

Unfortunately, educating customers is going to be harder, and will probably require a few rounds of back-and-forth on every customer issue :(

**Comment by tmds** [comment]
> on every customer issue

This makes it sound like _every customer issue_ but it is: _every customer issue about this example app_.
I hope we don't get many of those, because that means the customer has issues figuring out some basic stuff.

I'm fine with changes as long as they are easy to maintain when there's a new .NET version.

I prefer not to make changes that make things behave better on OpenShift, because that hides some essential learning the customer should do at some point for his own apps.

**Comment by tmds** [comment]
I'm going to close this. As indicated in the previous comment I would prefer to keep the effort in updating this repo for new .NET versions to the minimum.
